blank_issues_enabled: false
contact_links:
  - name: Home Assistant community thread
    url: https://community.home-assistant.io/t/ngbs-icon-integration-to-homeassistant/966557
    about: General discussion and help from other users
