#!/usr/bin/env bash
# Development Home Assistant (Docker, host network, http://localhost:8123).
#
# It uses the default port on purpose: a custom `http: server_port` is a trial
# configuration in Home Assistant 2026.9+, which reverts (and restarts) after five
# minutes unless it is confirmed over the WebSocket API.
#
#   scripts/dev-ha.sh up      create config/ on first run, start, finish onboarding
#   scripts/dev-ha.sh down    stop (config/ is kept)
#   scripts/dev-ha.sh logs    follow the log, integration lines only
#   scripts/dev-ha.sh reset   stop and delete config/ (fresh instance on next "up")
#
# The repository's custom_components/ is bind-mounted, so code changes only need a
# Home Assistant restart: docker restart ngbs-icon-dev-ha
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG_DIR=config

ensure_env() {
  [[ -f .env ]] || cp .env.example .env
  if ! grep -q '^DEV_HA_PASSWORD=.\+' .env; then
    local password
    password=$(python3 -c 'import secrets; print(secrets.token_urlsafe(18))')
    if grep -q '^DEV_HA_PASSWORD=' .env; then
      sed -i "s|^DEV_HA_PASSWORD=.*|DEV_HA_PASSWORD=${password}|" .env
    else
      echo "DEV_HA_PASSWORD=${password}" >> .env
    fi
  fi
}

write_config() {
  mkdir -p "${CONFIG_DIR}"
  [[ -f "${CONFIG_DIR}/configuration.yaml" ]] && return
  cat > "${CONFIG_DIR}/configuration.yaml" <<YAML
# Development instance for the NGBS iCON integration (generated by scripts/dev-ha.sh).
homeassistant:
  name: NGBS iCON development
  time_zone: Europe/Budapest
  country: HU
  unit_system: metric
  currency: HUF

# Only what integration development needs; default_config would also start Bluetooth,
# which cannot work in the container and only produces errors.
config:
dhcp:
network:
frontend:
history:
logbook:
search:
system_health:
diagnostics:
repairs:

logger:
  default: info
  logs:
    custom_components.ngbs_icon: debug
    pyngbsicon: debug
YAML
}

onboard() {
  python3 - <<'PY'
import json, sys, time, urllib.error, urllib.parse, urllib.request
from pathlib import Path

sys.path.insert(0, "scripts")
from devenv import load_env

env = load_env()
base = env.get("DEV_HA_URL", "http://localhost:8123").rstrip("/")
client_id = base + "/"

def call(method, path, data=None, token=None, form=False):
    body = None
    headers = {}
    if data is not None:
        if form:
            body = urllib.parse.urlencode(data).encode()
            headers["Content-Type"] = "application/x-www-form-urlencoded"
        else:
            body = json.dumps(data).encode()
            headers["Content-Type"] = "application/json"
    if token:
        headers["Authorization"] = "Bearer " + token
    request = urllib.request.Request(base + path, data=body, headers=headers, method=method)
    with urllib.request.urlopen(request, timeout=10) as response:
        text = response.read().decode()
        return json.loads(text) if text else {}

for _ in range(120):
    try:
        steps = call("GET", "/api/onboarding")
        break
    except (urllib.error.URLError, ConnectionError, TimeoutError):
        time.sleep(2)
else:
    raise SystemExit("Home Assistant did not come up on " + base)

done = {step["step"] for step in steps if step["done"]}
if "user" in done:
    print("Onboarding already complete.")
    raise SystemExit(0)

auth = call("POST", "/api/onboarding/users", {
    "client_id": client_id, "name": "Developer", "username": env["DEV_HA_USER"],
    "password": env["DEV_HA_PASSWORD"], "language": "en",
})
token = call("POST", "/auth/token", {
    "grant_type": "authorization_code", "code": auth["auth_code"], "client_id": client_id,
}, form=True)["access_token"]
for step, payload in (("core_config", {}), ("analytics", {}),
                      ("integration", {"client_id": client_id, "redirect_uri": client_id})):
    try:
        call("POST", f"/api/onboarding/{step}", payload, token=token)
    except urllib.error.HTTPError as err:
        if err.code != 403:  # 403 = step already done
            raise
print(f"Onboarding complete: {base}  user {env['DEV_HA_USER']} (password in .env)")
PY
}

case "${1:-}" in
  up)
    ensure_env
    write_config
    docker compose up -d ha
    onboard
    ;;
  down)
    docker compose stop ha
    ;;
  logs)
    docker compose logs -f --tail=200 ha | grep --line-buffered -iE 'ngbs|pyngbsicon|error'
    ;;
  reset)
    docker compose rm -sf ha
    # config/ is written by the container as root; remove it from a container as well.
    docker run --rm -v "$(pwd)/${CONFIG_DIR}:/c" alpine sh -c 'rm -rf /c/* /c/.[!.]*' || true
    rmdir "${CONFIG_DIR}" 2>/dev/null || true
    ;;
  *)
    echo "usage: $0 up|down|logs|reset" >&2
    exit 2
    ;;
esac
